export const REPLAY_COLORS = {
  cream: "#f5f3ed",
  floor: "#e8e5dc",
  wall: "#ded9cf",
  paper: "#f7f3e9",
  paperWarm: "#eee6d3",
  paperAged: "#e4d19a",
  cork: "#d8ccb6",
  wood: "#b79f7b",
  woodDark: "#756756",
  metal: "#676b68",
  metalDark: "#3d423f",
  concrete: "#c9c6bd",
  glass: "#b9d1cc",
  fabricDark: "#364149",
  plastic: "#d8d4c9",
  ink: "#111111",
  mutedInk: "#66635d",
  amber: "#d99a20",
  yellow: "#f4c94f",
  red: "#d64a4a",
  green: "#2baf83",
  blue: "#356edb",
} as const;

export const REPLAY_MATERIALS = {
  paper: { color: REPLAY_COLORS.paper, roughness: 0.94 },
  agedPaper: { color: REPLAY_COLORS.paperWarm, roughness: 0.96 },
  wood: { color: REPLAY_COLORS.wood, roughness: 0.82 },
  metal: { color: REPLAY_COLORS.metal, roughness: 0.42, metalness: 0.46 },
  darkMetal: { color: REPLAY_COLORS.metalDark, roughness: 0.38, metalness: 0.58 },
  plastic: { color: REPLAY_COLORS.plastic, roughness: 0.68 },
  glass: {
    color: REPLAY_COLORS.glass,
    roughness: 0.16,
    transmission: 0.28,
    transparent: true,
    opacity: 0.34,
  },
} as const;
