"use client";
import { navigateAccountBoundary } from "@/lib/account-navigation";
import Link from "next/link";
import { useState,useEffect,useRef,type FormEvent } from "react";
import { ThemeToggle } from "@/components/theme-toggle";
import { createPrivateInvestigation,getInvestigations } from "@/lib/crimelens-api";
export function PrivateCases({creating=false}:{creating?:boolean}){
  const [cases,setCases]=useState<Awaited<ReturnType<typeof getInvestigations>>>([]);
  const [name,setName]=useState("");const [description,setDescription]=useState("");
  const [message,setMessage]=useState(creating ? "" : "Loading your cases…");const [busy,setBusy]=useState(false);
  const retry=useRef<{key:string;content:string}|null>(null); const inFlight=useRef(false);
  useEffect(()=>{if(creating)return;const controller=new AbortController();void getInvestigations(controller.signal).then(items=>{setCases(items);setMessage(items.length ? "" : "Your first investigation starts here.");}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return ()=>controller.abort();},[creating]);
  async function create(event:FormEvent){event.preventDefault();if(inFlight.current)return;inFlight.current=true;setBusy(true);setMessage("");try{const content=JSON.stringify([name.trim(),description.trim()]);if(retry.current?.content!==content)retry.current={key:crypto.randomUUID(),content};const result=await createPrivateInvestigation({name:name.trim(),description:description.trim(),requestId:retry.current.key});const view=new URLSearchParams(window.location.search).get("view");navigateAccountBoundary(`/workspace?investigation=${encodeURIComponent(result.id)}${view === "evidence" ? "&view=evidence" : ""}`);}catch(e){setMessage(e instanceof Error ? e.message : "Case creation failed. Retry safely.");}finally{inFlight.current=false;setBusy(false);}}
  return <main className="cases-page"><header><Link href="/">← The Fatal Ledger</Link><ThemeToggle/></header><p className="archive-eyebrow">YOUR PRIVATE CASE DESK</p><h1>{creating ? "Open a new investigation." : "Your investigations."}</h1>{creating ? <form className="case-form" onSubmit={create}><p className="text-xs leading-6">Start with a name and a question. Only you can access this case until membership is explicitly granted.</p><label htmlFor="case-name">Case name</label><input id="case-name" required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="case-description">What are you investigating? (optional)</label><textarea id="case-description" maxLength={2000} rows={4} value={description} onChange={e=>setDescription(e.target.value)}/><button className="archive-button" disabled={busy}>{busy ? "Creating your case…" : "Create private case →"}</button></form> : <><Link className="archive-button my-6 max-w-sm" href="/cases/new">+ New investigation</Link><div className="guest-list">{cases.map(c=><article key={c.id}><small>{c.type}</small><h3>{c.name}</h3><Link className="archive-button" href={`/workspace?investigation=${encodeURIComponent(c.id)}`}>Open case →</Link></article>)}</div></>}<p role="status" className="my-6">{message}</p><Link href={creating ? "/cases" : "/"}>{creating ? "← Your cases" : "Explore the public archive ↗"}</Link></main>;
}
